# Generated by Django 5.0.1 on 2024-02-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_homepage_image_ar_alter_homepage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='image'),
        ),
    ]
